namespace Example.PoC;

// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
public partial class Patient : global::Avro.Specific.ISpecificRecord
{
	public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Patient\",\"namespace\":\"Example.PoC\",\"fields\":[{\"name\":\"Pa" +
	                                                                      "tientId\",\"type\":\"string\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"DateOfBirth\"," +
	                                                                      "\"type\":\"string\"}]}");
	private string _PatientId;
	private string _Name;
	private string _DateOfBirth;
	public virtual global::Avro.Schema Schema
	{
		get
		{
			return Patient._SCHEMA;
		}
	}
	public string PatientId
	{
		get
		{
			return this._PatientId;
		}
		set
		{
			this._PatientId = value;
		}
	}
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			this._Name = value;
		}
	}
	public string DateOfBirth
	{
		get
		{
			return this._DateOfBirth;
		}
		set
		{
			this._DateOfBirth = value;
		}
	}
	public virtual object Get(int fieldPos)
	{
		switch (fieldPos)
		{
			case 0: return this.PatientId;
			case 1: return this.Name;
			case 2: return this.DateOfBirth;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
		}
		;
	}
	public virtual void Put(int fieldPos, object fieldValue)
	{
		switch (fieldPos)
		{
			case 0: this.PatientId = (System.String)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.DateOfBirth = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
		}
		;
	}
}



